dev-deployment:
 variables:
   GIT_STRATEGY: fetch
 script:
   - - bash ~/gitlab/NextJS/nextjs-giftlistdeploy.sh
 environment:
     name: Development
     url : https://aurora-ui.dedicateddevelopers.us/
 tags:
   - node-docker
 only:
   - dev 

